### ISSUE TITLE
Build failed with GDAL 3.0.4

### ISSUE THREAD

**Issue by dezhin** [nextgis/cesium-terrain-builder#1]
After migration from Ubuntu 18.04 (everything works fine) I'm trying to build on Ubuntu 20.04 and have got following error:

```$ cmake ./
$ make
Scanning dependencies of target ctb
[  4%] Building CXX object src/CMakeFiles/ctb.dir/GDALTile.cpp.o
[  8%] Building CXX object src/CMakeFiles/ctb.dir/GDALTiler.cpp.o
In file included from /home/jean/gis/cesium-terrain-builder/src/GDALTiler.cpp:213:
/home/jean/gis/cesium-terrain-builder/src/gdaloverviewdataset.cpp:90:17: error: ‘const char* GDALOverviewDataset::GetProjectionRef()’ marked ‘override’, but does not override
   90 |     const char *GetProjectionRef( void ) override;
      |                 ^~~~~~~~~~~~~~~~
/home/jean/gis/cesium-terrain-builder/src/gdaloverviewdataset.cpp:94:17: error: ‘const char* GDALOverviewDataset::GetGCPProjection()’ marked ‘override’, but does not override
   94 |     const char *GetGCPProjection() override;
      |                 ^~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/ctb.dir/build.make:76: src/CMakeFiles/ctb.dir/GDALTiler.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: src/CMakeFiles/ctb.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
